### ISSUE TITLE
Missing "version" in package.json

### ISSUE THREAD

**Issue by TwizzyDizzy** [FH-Potsdam/shifted-maps#44]
Hi @lennerd,

just tried to install shifted-maps. A minor bug: Your package.json does not contain a version string, that seems to be mandatory.

> root@debian-jessie:/opt# npm install ./shifted-maps
> npm ERR! addLocal Could not install /opt/shifted-maps
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/opt/node-v4.1.2-linux-x64/bin/node" "/opt/node-v4.1.2-linux-x64/bin/npm" "install" > "./shifted-maps"
> npm ERR! node v4.1.2
> npm ERR! npm  v2.14.4
> 
> npm ERR! No version provided in package.json
> npm ERR! 
> npm ERR! If you need help, you may report this error at:
> npm ERR!     https://github.com/npm/npm/issues
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /opt/npm-debug.log

Adding a version string to package.json like so:

> {
>   "name": "shifted-maps-web",
>   "license": "GPL-3.0",
>   "version": "1.0.0",
>   "bugs": {
>     "url": "https://github.com/FH-Potsdam/shifted-maps/issues"
>   },
> [...]

does fix this.

Cheers
Thomas

**Comment by lennerd** [comment]
Hey @TwizzyDizzy 

thanks again for your interest. I added a README file, better instructions for the installation, a better installation process and the missing package.json fields. Tell us what you think. :wink:
