### ISSUE TITLE
Update or archive

### ISSUE THREAD

**Issue by ff6347** [FH-Potsdam/shifted-maps#51]
@lennerd  If this project is no longer maintained it should be archived due to security vulnerabilities see https://github.com/FH-Potsdam/shifted-maps/network/alerts

**Comment by lennerd** [comment]
Hey @fabianmoronzirfas,

thanks for the hint. Turned off my email notification, should change that.

I will take a look and make an update.

**Comment by lennerd** [comment]
Just made an update and removed the old library.

(Still love now.sh! Really amazed how easy it is to get back into the project code and deploy everything easily and in minutes.)

Anyway. Thanks for the hint.

**Comment by ff6347** [comment]
Great. Did you know that they got a version 2? Your `now.json` looks like v1

- https://zeit.co/examples/static
- https://zeit.co/docs/v2/deployments/configuration

**Comment by lennerd** [comment]
Yes, I know. Really nice. Should be no big to change that. Didn‘t had the time to adjust the Next.js application yet.
