### ISSUE TITLE
Resolved 2

### ISSUE THREAD

**Issue by GISScience** [FH-Potsdam/shifted-maps#53]
I am new

**Comment by lennerd** [comment]
Seems like your missing the `ThemeProvider` component wrapping your application or at least the parts from Shifted Maps.

https://github.com/FH-Potsdam/shifted-maps/blob/c4c64c8734668c7007a95bd777562ddc5c35154c/pages/_app.tsx#L90
https://www.styled-components.com/docs/advanced#theming

**Comment by lennerd** [comment]
Closed due to inactivity. Will reopen if necessary.
